version: "3.3"
services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - pyfinance_network

networks:
  pyfinance_network:
    driver: bridge
